### ISSUE TITLE
Neuss != Moers

### ISSUE THREAD

**Issue by paintdog** [P3nny/fna-geschichtsstationen#1]
1. Neuss ist nicht Moers, jedenfalls sind entweder die Daten falsch oder der Name der App :)
2. tippo: "First News App: Geschichtssationen Neuss" > "First News App: Geschichtss**_t_**ationen Neuss"

BTW: Gibt es einen Bezug zu Neuss - ich folge dem Account eigentlich wg. DjangoGirls-Aktivitäten in Köln...

**Comment by P3nny** [comment]
Huch .... mir war schon klar, dass ich bei GitHub öffentliche Repos erstelle, aber bislang dachte ich nicht, dass sich irgendwer dafür interessiert :) 
Das freut mich natürlich einerseits, heißt aber, dass ich nicht mehr völlig verpeilte READMEs erstellen sollte. 
Zu Moers: Dort findet am 09. und 10.04 ein Open Data Hackday statt. Veranstalter Claus Arndt von der Stadt Moers hat mich gefragt, ob ich da eine Art 'Data4Girls' veranstalte, also eine Einführung in die Arbeit mit offenen Daten, Visualisierung und  News Apps. 
Und dafür habe ich gestern auf die Schnelle angefangen, die "First News App" auf Moerser Daten zu übertragen. Problem: In der News App wird mit .csv Daten gearbeitet, Moers stellt Json bereit. Damit war mein Hirn beschäftigt, als es Neuss schrieb. 
LG, Patricia, die jetzt mal guckt, ob Du mein einziger Follower bist ....
